import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { WorkspaceShell } from "@/components/workspace-shell";
import { createClient } from "@/lib/supabase/server";
import { deleteRecord, updateRecord } from "../../actions";

const entities={companies:{label:"شرکت",table:"companies"},contacts:{label:"مخاطب",table:"contacts"},leads:{label:"سرنخ",table:"leads"},deals:{label:"معامله",table:"deals"},activities:{label:"فعالیت",table:"activities"}} as const;
type Entity=keyof typeof entities;
type Props={params:Promise<{organizationId:string;entity:string;recordId:string}>;searchParams:Promise<{error?:string;success?:string}>};

export default async function RecordPage({params,searchParams}:Props){
 const [{organizationId,entity:rawEntity,recordId},query]=await Promise.all([params,searchParams]);
 if(!(rawEntity in entities))notFound(); const entity=rawEntity as Entity; const supabase=await createClient();
 const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect("/auth");
 const [{data:organization},{data:membership},{data:record},{data:companies}]=await Promise.all([
  supabase.from("organizations").select("id,name").eq("id",organizationId).maybeSingle(),
  supabase.from("organization_memberships").select("role").eq("organization_id",organizationId).eq("user_id",user.id).eq("status","active").maybeSingle(),
  supabase.from(entities[entity].table).select("*").eq("id",recordId).eq("organization_id",organizationId).maybeSingle(),
  supabase.from("companies").select("id,name").eq("organization_id",organizationId).order("name")
 ]); if(!organization||!membership||!record)notFound();
 const title=String(record.name??record.title??`${record.first_name??""} ${record.last_name??""}`.trim()??entities[entity].label);
 return <WorkspaceShell organizationId={organizationId} organizationName={organization.name} email={user.email??"U"} active="crm"><div className="page-wrap record-page">
  <div className="breadcrumb"><Link href={`/dashboard/${organizationId}/crm?tab=${entity}`}>CRM</Link><span>←</span><span>{entities[entity].label}</span></div>
  <section className="record-hero"><div className="record-avatar">{title.slice(0,1)}</div><div><p>{entities[entity].label}</p><h1>{title}</h1><div className="record-meta"><span>شناسه: {recordId.slice(0,8)}</span><span>ایجاد: {new Date(String(record.created_at)).toLocaleDateString("fa-IR")}</span></div></div><div className="record-actions"><Link className="btn" href={`/dashboard/${organizationId}/crm?tab=${entity}`}>بازگشت به فهرست</Link></div></section>
  {query.error&&<p className="form-message error notice">{query.error}</p>}{query.success&&<p className="form-message success notice">تغییرات با موفقیت ذخیره شد.</p>}
  <div className="record-layout"><section className="surface detail-panel"><div className="surface-head"><div><small>اطلاعات اصلی</small><h2>ویرایش {entities[entity].label}</h2></div><span className="status-dot">فعال</span></div><EditForm entity={entity} organizationId={organizationId} recordId={recordId} record={record as Record<string,unknown>} companies={companies??[]}/></section>
  <aside className="record-aside"><section className="surface timeline"><div className="surface-head"><h2>خط زمانی</h2></div><div className="timeline-item"><i/><div><strong>رکورد ایجاد شد</strong><p>{new Date(String(record.created_at)).toLocaleString("fa-IR")}</p></div></div><div className="timeline-empty">فعالیت‌های مرتبط بعدی در اینجا نمایش داده می‌شوند.</div></section><section className="surface danger-zone"><h3>حذف رکورد</h3><p>این عملیات قابل بازگشت نیست و ممکن است ارتباطات وابسته را نیز حذف کند.</p><form action={deleteRecord}><Hidden organizationId={organizationId} entity={entity} recordId={recordId}/><button className="btn btn-danger">حذف این {entities[entity].label}</button></form></section></aside></div>
 </div></WorkspaceShell>;
}

function Hidden({organizationId,entity,recordId}:{organizationId:string;entity:Entity;recordId:string}){return <><input type="hidden" name="organizationId" value={organizationId}/><input type="hidden" name="entity" value={entity}/><input type="hidden" name="recordId" value={recordId}/></>}
function Input({label,name,value,type="text"}:{label:string;name:string;value:unknown;type?:string}){return <label>{label}<input name={name} type={type} defaultValue={String(value??"")}/></label>}
function EditForm({entity,organizationId,recordId,record,companies}:{entity:Entity;organizationId:string;recordId:string;record:Record<string,unknown>;companies:Array<{id:string;name:string}>}){return <form className="detail-form" action={updateRecord}><Hidden organizationId={organizationId} entity={entity} recordId={recordId}/>
 {entity==="companies"&&<><Input label="نام شرکت" name="name" value={record.name}/><Input label="شماره تماس" name="phone" value={record.phone}/><Input label="حوزه فعالیت" name="industry" value={record.industry}/><Input label="شهر" name="city" value={record.city}/><Input label="وب‌سایت" name="website" value={record.website}/></>}
 {entity==="contacts"&&<><Input label="نام" name="firstName" value={record.first_name}/><Input label="نام خانوادگی" name="lastName" value={record.last_name}/><label>شرکت<select name="companyId" defaultValue={String(record.company_id??"")}><option value="">بدون شرکت</option>{companies.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><Input label="شماره تماس" name="phone" value={record.phone}/><Input label="ایمیل" name="email" value={record.email} type="email"/><Input label="سمت" name="jobTitle" value={record.job_title}/></>}
 {entity==="leads"&&<><Input label="عنوان سرنخ" name="title" value={record.title}/><Input label="نام" name="firstName" value={record.first_name}/><Input label="نام خانوادگی" name="lastName" value={record.last_name}/><Input label="شرکت" name="companyName" value={record.company_name}/><Input label="شماره تماس" name="phone" value={record.phone}/><Input label="ایمیل" name="email" value={record.email} type="email"/><Input label="منبع" name="source" value={record.source}/><Input label="امتیاز" name="score" value={record.score} type="number"/><label>وضعیت<select name="status" defaultValue={String(record.status)}><option value="new">جدید</option><option value="working">در حال پیگیری</option><option value="qualified">واجد شرایط</option><option value="unqualified">ردشده</option><option value="converted">تبدیل‌شده</option></select></label></>}
 {entity==="deals"&&<><Input label="عنوان معامله" name="title" value={record.title}/><Input label="مبلغ" name="amount" value={record.amount} type="number"/><label>ارز<select name="currency" defaultValue={String(record.currency)}><option value="IRR">ریال</option><option value="USD">دلار</option><option value="EUR">یورو</option></select></label><label>شرکت<select name="companyId" defaultValue={String(record.company_id??"")}><option value="">بدون شرکت</option>{companies.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><Input label="تاریخ پیش‌بینی بسته‌شدن" name="expectedCloseDate" value={record.expected_close_date} type="date"/><label>وضعیت<select name="status" defaultValue={String(record.status)}><option value="open">باز</option><option value="won">برنده</option><option value="lost">از دست رفته</option></select></label></>}
 {entity==="activities"&&<><Input label="موضوع" name="subject" value={record.subject}/><label>نوع<select name="type" defaultValue={String(record.type)}><option value="task">وظیفه</option><option value="call">تماس</option><option value="meeting">جلسه</option><option value="email">ایمیل</option><option value="note">یادداشت</option></select></label><Input label="سررسید" name="dueAt" value={record.due_at?String(record.due_at).slice(0,16):""} type="datetime-local"/><label className="full">توضیحات<textarea name="description" defaultValue={String(record.description??"")}/></label></>}
 <div className="form-footer"><button className="btn btn-primary">ذخیره تغییرات</button><Link className="btn" href={`/dashboard/${organizationId}/crm?tab=${entity}`}>انصراف</Link></div></form>}
